frontend/models/Challenge.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "challenge".
 *
 * @property integer $id
 * @property string $sub_category_id
 * @property string $date_start
 * @property string $date_stop
 * @property string $description
 * @property string $expected_result
 */
class Challenge extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'challenge';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sub_category_id'], 'required'],
            [['date_start', 'date_stop', 'description'], 'safe'],
            [['sub_category_id'], 'string', 'max' => 45],
            [['expected_result'], 'string', 'max' => 50],
            [['description'], 'string', 'max' => 2000],
            [['title'], 'string', 'max' => 64],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'sub_category_id' => 'Challenge',
            'date_start' => 'Date Start',
            'date_stop' => 'Date Stop',
            'description' => 'Description',
            'title' => 'Title',
            'expected_result' => 'Expected Result',
        ];
    }

    public function getSubcategoryName()
    {
        $subCategory = SubCategory::findOne($this->sub_category_id);

        return isset($subCategory) ? $subCategory->name : 'NA';
    }

    public function getChallengeName()
    {
        $challenge = Challenge::findOne($this->challenge_id);

        return isset($challenge) ? 'TBD' : 'NA';
    }

    public function getSubcategory()
    {
        return $this->hasOne(SubCategory::className(), 'sub_category_id', 'id');
    }
}

frontend/controllers/ChallengeController.php
<?php

namespace frontend\controllers;

use frontend\models\Category;
use frontend\models\SubCategory;
use Yii;
use frontend\models\Challenge;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * ChallengeController implements the CRUD actions for Challenge model.
 */
class ChallengeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Challenge models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Challenge::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionPlaynow()
    {
        $categories = Category::find()->all();

        foreach ($categories as $category) {
            $query = (new Query())
                ->select(['challenge.id AS id', 'sub_category.id AS sub_category_id', 'sub_category.name AS sub_category_name', 'challenge.title AS challenge_title', 'date_stop'])
                ->from('challenge')
                ->innerJoin('sub_category', 'sub_category_id = `sub_category`.id')
                ->innerJoin('category', 'category_id = category.id')
                ->where(['category.id'=>$category->id])
                ->limit(25);

            $dataProviders[$category->name] = new ActiveDataProvider([
                'query' => $query
            ]);
        }

        return $this->render('playnow', [
            'dataProviders' => $dataProviders,
        ]);
    }

    /**
     * Displays a single Challenge model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Challenge model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Challenge();
        $categories = Category::find()->select(['id', 'name'])->all();

        foreach($categories as $category) {
            $subcategory = SubCategory::find()->where(['category_id' => $category->id])->all();

            if(! empty($subcategory)) {
                $list[$category->name] = ArrayHelper::map($subcategory, 'id', 'name');
            }
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'subcategories' => $list
        ]);
    }

    /**
     * Updates an existing Challenge model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $subcategories = ArrayHelper::map(SubCategory::find()->select(['id', 'name'])->all(), 'id', 'name');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'subcategories' => $subcategories
        ]);

    }

    /**
     * Deletes an existing Challenge model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Challenge model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Challenge the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Challenge::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/challenge/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use kartik\widgets\DateTimePicker;

/* @var $this yii\web\View */
/* @var $model frontend\models\Challenge */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="challenge-form box">

    <?php $form = ActiveForm::begin(); ?>

    <?php
        echo $form->field($model, 'sub_category_id')->widget(Select2::classname(), [
          'data' => $subcategories,
          'language' => 'en',
          'options' => ['placeholder' => 'Select a Subcategory'],
          'pluginOptions' => [
            'allowClear' => true
          ],
        ]);
    ?>

    <?php
        echo $form->field($model, 'date_start')->widget(DateTimePicker::className([
              'options' => ['placeholder' => 'Select operating time ...'],
              'type' => DateTimePicker::TYPE_COMPONENT_PREPEND,
              'layout' => '{picker}{input}{remove}',
              'pluginOptions' => [
                'format' => 'dd-MM-yyyy h:i:s',
                'autoclose' => true,
              ]
            ])
        );
    ?>

    <?php
        echo $form->field($model, 'date_stop')->widget(DateTimePicker::className([
                'options' => ['placeholder' => 'Select operating time ...'],
                'type' => DateTimePicker::TYPE_COMPONENT_PREPEND,
                'layout' => '{picker}{input}{remove}',
                'pluginOptions' => [
                    'format' => 'dd-MM-yyyy h:i:s',
                    'autoclose' => true,
                ]
            ])
        );
    ?>

    <?= $form->field($model, 'title')->textInput() ?>
    <?= $form->field($model, 'description')->textarea(['rows'=>10]) ?>

    <?= $form->field($model, 'expected_result')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/challenge/_playnow.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
?>

<?php

echo
GridView::widget([
	'dataProvider' => $dataProvider,
	'layout'=>"{items}",
	'columns' => [
		[
			'header' => 'Sub Category',
			'value' => function($data) {
				return  $data['sub_category_name']; //$model->getSubcategoryName();
			}
		],
		[
			'header' => 'Ending Time',
			'value' => function($data){
				return '<span class="glyphicon glyphicon-download"></span>  ' . $data['date_stop'] ;
			},
			'format' => 'html'
		],
		[
			'header' => 'Challenge',
			'value' => 'challenge_title'
		],
		[
			'class' => 'yii\grid\ActionColumn',
			'template' => '{view}',
			'buttons' => [
				'view' => function ($url, $data) {
					return Html::a('<span class="glyphicon glyphicon-eye-open"></span>',
						Url::to(['challenge/view', 'id'=>$data['id']]), [
							'title' => Yii::t('app', 'View Challenge'),
						]);
				}
			]
		],
	],
]); ?>

frontend/views/challenge/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\Challenge */

$this->title = 'Create Challenge';
$this->params['breadcrumbs'][] = ['label' => 'Challenges', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="challenge-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'subcategories' => $subcategories
    ]) ?>

</div>

frontend/views/challenge/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Challenges';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="challenge-index box">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Challenge', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'sub_category_id',
                'value' => function($model) {
                    return $model->getSubcategoryName();
                }
            ],

            'date_start',
            'date_stop',
            'title',
            // 'expected_result',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

frontend/views/challenge/playnow.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Play Now';
?>

<div class="challenge-index box">
    <?php foreach ($dataProviders as $name => $dataProvider) :  ?>
        <h1><?= Html::encode($name) ?></h1>

        <?php echo $this->render('_playnow', ['dataProvider' => $dataProvider])?>

    <?php endforeach; ?>
</div>

frontend/views/challenge/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Challenge */

$this->title = 'Update Challenge: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Challenges', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="challenge-update box">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'subcategories' => $subcategories
    ]) ?>

</div>

frontend/views/challenge/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\Challenge */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Challenges', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="challenge-view box">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'sub_category_id',
            'date_start',
            'date_stop',
            'description',
            'expected_result',
            'title',
        ],
    ]) ?>

</div>