frontend/controllers/PronomenController.php
<?php

namespace frontend\controllers;

class PronomenController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionPersonliga()
    {
        return $this->render('personliga');
    }

    public function actionReflexiva()
    {
        return $this->render('reflexiva');
    }

    public function actionPossessiva()
    {
        return $this->render('possessiva');
    }

    public function actionReflexivapossessiva()
    {
        return $this->render('reflexivapossessiva');
    }

}

frontend/views/pronomen/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
?>

<div class="box">
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <br><br>
            <?=  Html::a('Pronomen', ['pronomen/index'], ['class'=>'btn btn-default'] )?>
            <?=  Html::a('Personliga', ['pronomen/personliga'], ['class'=>'btn btn-success'] )?>
            <?=  Html::a('Reflexiva', ['/pronomen/reflexiva'], ['class'=>'btn btn-danger'] )?>
            <?=  Html::a('Possessiva', ['/pronomen/possessiva'], ['class'=>'btn btn-warning'] )?>
            <?=  Html::a('Reflexiva possessiva', ['/pronomen/reflexivapossessiva'], ['class'=>'btn btn-info'] )?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <h1>Pronomen</h1>
            <p>A pronoun replaces a noun or stands in front of a noun.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-offset-1 col-md-4">
            <h3>Personliga</h3>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Subjekt</th>
                    <th>Objekt</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td colspan="2"><strong>First person</strong></td>
                </tr>
                <tr>
                    <td>jag</td>
                    <td>mig</td>
                </tr>
                <tr>
                    <td>vi</td>
                    <td>oss</td>
                </tr>

                <tr>
                    <td colspan="2"><strong>Second person</strong></td>
                </tr>
                <tr>
                    <td>du</td>
                    <td>dig</td>
                </tr>
                <tr>
                    <td>ni</td>
                    <td>er</td>
                </tr>


                <tr>
                    <td colspan="2"><strong>Third person</strong></td>
                </tr>
                <tr>
                    <td>han</td>
                    <td>honom</td>
                </tr>
                <tr>
                    <td>hon</td>
                    <td>henne</td>
                </tr>
                <tr>
                    <td>de</td>
                    <td>dem</td>
                </tr>
                <tr>
                    <td>den</td>
                    <td>den</td>
                </tr>
                <tr>
                    <td>det</td>
                    <td>det</td>
                </tr>
                <tr>
                    <td>man</td>
                    <td>en</td>
                </tr>

                </tbody>
            </table>
        </div>

        <div class="col-md-offset-1 col-md-4">
            <h3>Reflexiva</h3>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th colspan="2"><--------------------|</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td colspan="2"><strong>First person</strong></td>
                </tr>
                <tr>
                    <td>jag</td>
                    <td>mig</td>
                </tr>
                <tr>
                    <td>vi</td>
                    <td>oss</td>
                </tr>

                <tr>
                    <td colspan="2"><strong>Second person</strong></td>
                </tr>
                <tr>
                    <td>du</td>
                    <td>dig</td>
                </tr>
                <tr>
                    <td>ni</td>
                    <td>er</td>
                </tr>

                <tr>
                    <td colspan="2"><strong>Third person</strong></td>
                </tr>
                <tr>
                    <td>han</td>
                    <td>sig</td>
                </tr>
                <tr>
                    <td>hon</td>
                    <td>sig</td>
                </tr>
                <tr>
                    <td>de</td>
                    <td>sig</td>
                </tr>
                <tr>
                    <td>den</td>
                    <td>sig</td>
                </tr>
                <tr>
                    <td>det</td>
                    <td>sig</td>
                </tr>
                <tr>
                    <td>man</td>
                    <td>sig</td>
                </tr>

                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-offset-1 col-md-4">
            <h3>Possessiva</h3>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>pronomen</th>
                    <th>en ord</th>
                    <th>ett ord</th>
                    <th>plural</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td colspan="4"><strong>First person</strong></td>
                </tr>
                <tr>
                    <td>jag</td>
                    <td>min</td>
                    <td>mitt</td>
                    <td>mina</td>
                </tr>
                <tr>
                    <td>vi</td>
                    <td>vår</td>
                    <td>vårt</td>
                    <td>våra</td>
                </tr>

                <tr>
                    <td colspan="4"><strong>Second person</strong></td>
                </tr>
                <tr>
                    <td>du</td>
                    <td>din</td>
                    <td>ditt</td>
                    <td>dina</td>
                </tr>
                <tr>
                    <td>ni</td>
                    <td>er</td>
                    <td>ert</td>
                    <td>era</td>
                </tr>


                <tr>
                    <td colspan="4"><strong>Third person</strong></td>
                </tr>
                <tr>
                    <td>han</td>
                    <td>hans</td>
                    <td>hans</td>
                    <td>hans</td>
                </tr>
                <tr>
                    <td>hon</td>
                    <td>hennes</td>
                    <td>hennes</td>
                    <td>hennes</td>
                </tr>
                <tr>
                    <td>de</td>
                    <td>deras</td>
                    <td>deras</td>
                    <td>deras</td>
                </tr>
                <tr>
                    <td>den</td>
                    <td>dess</td>
                    <td>dess</td>
                    <td>dess</td>
                </tr>
                <tr>
                    <td>det</td>
                    <td>dess</td>
                    <td>dess</td>
                    <td>dess</td>
                </tr>
                <tr>
                    <td>man</td>
                    <td>ens</td>
                    <td>ens</td>
                    <td>ens</td>
                </tr>

                </tbody>
            </table>
        </div>

        <div class="col-md-offset-1 col-md-4">
            <h3>Reflexiva possessiva</h3>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>pronomen</th>
                    <th>en ord</th>
                    <th>ett ord</th>
                    <th>plural</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td colspan="4"><strong>First person</strong></td>
                </tr>
                <tr>
                    <td>jag</td>
                    <td>min</td>
                    <td>mitt</td>
                    <td>mina</td>
                </tr>
                <tr>
                    <td>vi</td>
                    <td>vår</td>
                    <td>vårt</td>
                    <td>våra</td>
                </tr>

                <tr>
                    <td colspan="4"><strong>Second person</strong></td>
                </tr>
                <tr>
                    <td>du</td>
                    <td>din</td>
                    <td>ditt</td>
                    <td>dina</td>
                </tr>
                <tr>
                    <td>ni</td>
                    <td>er</td>
                    <td>ert</td>
                    <td>era</td>
                </tr>


                <tr>
                    <td colspan="4"><strong>Third person</strong></td>
                </tr>
                <tr>
                    <td>han</td>
                    <td>sin</td>
                    <td>sitt</td>
                    <td>sina</td>
                </tr>
                <tr>
                    <td>hon</td>
                    <td>sin</td>
                    <td>sitt</td>
                    <td>sina</td>
                </tr>
                <tr>
                    <td>de</td>
                    <td>sin</td>
                    <td>sitt</td>
                    <td>sina</td>
                </tr>
                <tr>
                    <td>den</td>
                    <td>sin</td>
                    <td>sitt</td>
                    <td>sina</td>
                </tr>
                <tr>
                    <td>det</td>
                    <td>sin</td>
                    <td>sitt</td>
                    <td>sina</td>
                </tr>
                <tr>
                    <td>man</td>
                    <td>sin</td>
                    <td>sitt</td>
                    <td>sina</td>
                </tr>

                </tbody>
            </table>
        </div>

    </div>

</div>

frontend/views/pronomen/personliga.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
?>

<div class="box">
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <br><br>
            <?=  Html::a('Pronomen', ['pronomen/index'], ['class'=>'btn btn-default'] )?>
            <?=  Html::a('Personliga', ['pronomen/personliga'], ['class'=>'btn btn-success'] )?>
            <?=  Html::a('Reflexiva', ['/pronomen/reflexiva'], ['class'=>'btn btn-danger'] )?>
            <?=  Html::a('Possessiva', ['/pronomen/possessiva'], ['class'=>'btn btn-warning'] )?>
            <?=  Html::a('Reflexiva possessiva', ['/pronomen/reflexivapossessiva'], ['class'=>'btn btn-info'] )?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <h1>Personliga pronomen</h1>
            <p>The following sentences contain personliga pronomen in subject and object forms.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Menning</th>
                    <th>Subjekt/Objekt</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Jag ska se en film i kväll. <strong>Den</strong> heter Agent X.</td>
                        <td>subjekt</td>
                    </tr>
                    <tr>
                        <td>Jaha. Jag ska se <strong>den</strong> på lördag.</td>
                        <td>objekt</td>
                    </tr>
                    <tr>
                        <td colspan="2">&nbsp;</td>
                    </tr>

                    <tr>
                        <td>Vilket snyggt jacka. Var har du köpt <strong>det</strong> ?</td>
                        <td>objekt</td>
                    </tr>
                    <tr>
                        <td>På Dressman. <strong>Det</strong> kostade bara 2000 kronor.</td>
                        <td>subjekt</td>
                    </tr>
                    <tr>
                        <td colspan="2">&nbsp;</td>
                    </tr>

                    <tr>
                        <td>Var är Blom och Erik?</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><strong>De</strong> är i skolan.</td>
                        <td>subjekt</td>
                    </tr>
                    <tr>
                        <td>Har du talat med <strong>dem</strong> idag ?</td>
                        <td>objekt</td>
                    </tr>

                    <tr>
                        <td colspan="2">&nbsp;</td>
                    </tr>

                    <tr>
                        <td>Var är dina böcker?</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><strong>De</strong> ligger på skrivbordet.</td>
                        <td>subjekt</td>
                    </tr>
                    <tr>
                        <td>Får jag låna <strong>dem</strong> ?</td>
                        <td>objekt</td>
                    </tr>
                    <tr>
                        <td>Javisst.</td>
                        <td>&nbsp;</td>
                    </tr>

                </tbody>
            </table>
        </div>

    </div>

</div>

frontend/views/pronomen/possessiva.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
?>

<div class="box">
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <br><br>
            <?=  Html::a('Pronomen', ['pronomen/index'], ['class'=>'btn btn-default'] )?>
            <?=  Html::a('Personliga', ['pronomen/personliga'], ['class'=>'btn btn-success'] )?>
            <?=  Html::a('Reflexiva', ['/pronomen/reflexiva'], ['class'=>'btn btn-danger'] )?>
            <?=  Html::a('Possessiva', ['/pronomen/possessiva'], ['class'=>'btn btn-warning'] )?>
            <?=  Html::a('Reflexiva possessiva', ['/pronomen/reflexivapossessiva'], ['class'=>'btn btn-info'] )?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <h1>Possessiva pronomen</h1>
            <p>Possessiva pronomen is used to explain who is owning something or has something.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Menning <--------------|</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Kalle</strong> har en bil. <strong>Hans</strong> bil står i garage på nätterna.</td>
                    </tr>

                    <tr>
                        <td>Eva lånar ofta <strong>hans</strong> bil.</td>
                    </tr>

                    <tr>
                        <td><strong>Kalle</strong> har ett job på en företag. <strong>Hans</strong> jobb är snart ledig.
                        Eva ska söka hans jobb.</td>
                    </tr>

                    <tr>
                        <td><strong>Elle</strong> har en hund. <strong>Hennes</strong> hund heter Jack. Grannarna passar ofta <strong>hennes</strong> hund.</td>
                    </tr>

                    <tr>
                        <td><strong>Man</strong> har en viss handstil. <strong>Ens</strong> handstil är personlig.
                        Somliga kan kanske inte läsa ens handstil.</td>
                    </tr>

                </tbody>
            </table>
        </div>

    </div>

</div>

frontend/views/pronomen/reflexiva.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
?>

<div class="box">
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <br><br>
            <?=  Html::a('Pronomen', ['pronomen/index'], ['class'=>'btn btn-default'] )?>
            <?=  Html::a('Personliga', ['pronomen/personliga'], ['class'=>'btn btn-success'] )?>
            <?=  Html::a('Reflexiva', ['/pronomen/reflexiva'], ['class'=>'btn btn-danger'] )?>
            <?=  Html::a('Possessiva', ['/pronomen/possessiva'], ['class'=>'btn btn-warning'] )?>
            <?=  Html::a('Reflexiva possessiva', ['/pronomen/reflexivapossessiva'], ['class'=>'btn btn-info'] )?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <h1>Reflexiva pronomen</h1>
            <p>Reflexiva pronomen links back to the subject in the phrase.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Menning <--------------|</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Jag</strong> tvättar <strong>mig</strong>.</td>
                    </tr>

                    <tr>
                        <td><strong>Du</strong> tvättar <strong>dig</strong>.</td>
                    </tr>

                    <tr>
                        <td><strong>Kalle</strong> tvättar <strong>sig</strong>.</td>
                    </tr>

                    <tr>
                        <td><strong>Man</strong> måste tvättar <strong>sig</strong>.</td>
                    </tr>

                    <tr>
                        <td><strong>Vi</strong> tvättar <strong>oss</strong>.</td>
                    </tr>

                    <tr>
                        <td><strong>Ni</strong> tvättar <strong>er</strong>.</td>
                    </tr>

                    <tr>
                        <td><strong>De</strong> tvättar <strong>sig</strong>.</td>
                    </tr>
                </tbody>
            </table>
        </div>

    </div>

</div>

frontend/views/pronomen/reflexivapossessiva.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
?>

<div class="box">
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <br><br>
            <?=  Html::a('Pronomen', ['pronomen/index'], ['class'=>'btn btn-default'] )?>
            <?=  Html::a('Personliga', ['pronomen/personliga'], ['class'=>'btn btn-success'] )?>
            <?=  Html::a('Reflexiva', ['/pronomen/reflexiva'], ['class'=>'btn btn-danger'] )?>
            <?=  Html::a('Possessiva', ['/pronomen/possessiva'], ['class'=>'btn btn-warning'] )?>
            <?=  Html::a('Reflexiva possessiva', ['/pronomen/reflexivapossessiva'], ['class'=>'btn btn-info'] )?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <h1>Reflexiva possessiva pronomen</h1>
            <p>Possessiva pronomen is used to explain who is owning something or has something and also linking back to subjekt.</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Menning</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Emma</strong> tycker inte om <strong>sin</strong> svärmor.</td>
                    </tr>

                    <tr>
                        <td><strong>Man</strong> måste göra <strong>sina</strong> läxor om man vill ha bra betyg.</td>
                    </tr>

                    <tr>
                        <td><strong>Alex</strong> köper ofta blommor till <strong>sin</strong> flickvän.</td>
                    </tr>

                </tbody>
            </table>
        </div>

    </div>

</div>